# Generated by Django 2.2.19 on 2021-12-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20211220_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
    ]
