version: '3'

services:

  app: &app

    build:
      context: .
      dockerfile: app/bin/Dockerfile

    image: e2stem_site
    container_name: e2stem_site

    volumes:
      - .:/e2stem.site   

    ports:
      - "8000:8000"

    command: /start





