# Generated by Django 2.2.19 on 2021-12-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20211220_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
