# Generated by Django 4.0 on 2022-04-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_blogpost_created_at_alter_student_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_en',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle_kh',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_kh',
            field=models.CharField(max_length=200),
        ),
    ]
