# Generated by Django 4.0 on 2022-05-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_blogpost_subtitle_en_blogpost_subtitle_kh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
